nodeLinker: node-modules
npmScopes:
  '@hsunpei':
    npmAlwaysAuth: true
    npmAuthToken: '${NPM_TOKEN}'
    npmRegistryServer: 'https://registry.npmjs.org'
npmRegistries:
  'https://npm.pkg.github.com/':
    npmAuthToken: '${GITHUB_TOKEN}'
  'https://registry.npmjs.org/':
    npmAuthToken: '${NPM_TOKEN}'
